name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to cPanel
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASS: ${{ secrets.CPANEL_PASS }}
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        run: |
          curl -u "$CPANEL_USER:$CPANEL_PASS" "https://$CPANEL_HOST:2083/frontend/x3/filemanager/upload.html?dir=public_html" -F "file=@path/to/your/application.zip"
