# Generated by Django 5.0.6 on 2024-05-19 13:07

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_club_remove_player_image_player_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='venue',
        ),
        migrations.DeleteModel(
            name='LeagueStanding',
        ),
        migrations.RemoveField(
            model_name='club',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='coachingstaff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coachingstaff',
            name='title',
        ),
        migrations.RemoveField(
            model_name='otherstaff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='otherstaff',
            name='title',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AddField(
            model_name='club',
            name='established_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(default='Default Location', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium',
            field=models.CharField(default='Default Stadium', max_length=100),
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='club',
            field=models.CharField(default='Default Club', max_length=50),
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='experience',
            field=models.CharField(default='1 years', max_length=50),
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='photo',
            field=models.ImageField(default='photos/staff/default.jpg', upload_to='photos/staff/'),
        ),
        migrations.AddField(
            model_name='coachingstaff',
            name='role',
            field=models.CharField(default='Coach', max_length=100),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='club',
            field=models.CharField(default='Default Club', max_length=50),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='experience',
            field=models.CharField(default='1 years', max_length=50),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='photo',
            field=models.ImageField(default='photos/staff/default.jpg', upload_to='photos/staff/'),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='role',
            field=models.CharField(default='Coach', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.club'),
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstaff',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otherstaff',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='photos/players/default.jpg', upload_to='photos/players/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Fixture',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
