# Generated by Django 5.0.6 on 2024-05-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_remove_fixture_away_team_remove_fixture_home_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
    ]
