# Generated by Django 5.0.6 on 2024-05-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_remove_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingstaff',
            name='date_of_birth',
        ),
    ]
