# Generated by Django 5.0.6 on 2024-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_remove_coachingstaff_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherStaff',
        ),
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='club_photos/'),
        ),
    ]
