# Generated by Django 5.0.6 on 2024-05-23 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_delete_otherstaff_club_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='home_ground',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.club'),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('competition', models.CharField(max_length=100)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='football.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.PositiveIntegerField()),
                ('away_team_score', models.PositiveIntegerField()),
                ('home_goal_details', models.TextField(blank=True, null=True)),
                ('away_goal_details', models.TextField(blank=True, null=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.fixture')),
            ],
        ),
    ]
