# Generated by Django 5.0.6 on 2024-05-23 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_team_coach_team_home_ground_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='fixture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchresult', to='football.fixture'),
        ),
    ]
