# Generated by Django 5.0.6 on 2024-05-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_rename_location_fixture_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_ground',
        ),
    ]
