# Generated by Django 5.0.6 on 2024-05-29 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_result_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team',
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_a_logo',
            field=models.ImageField(null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_a_name',
            field=models.CharField(default='Team A', max_length=255),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_b_logo',
            field=models.ImageField(null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_b_name',
            field=models.CharField(default='Team B', max_length=255),
        ),
        migrations.AddField(
            model_name='fixture',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='competition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue',
            field=models.CharField(max_length=255),
        ),
    ]
