# Generated by Django 5.0.6 on 2024-06-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_alter_coachingstaff_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstaff',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoachingStaff', to='football.club'),
        ),
    ]
