# Generated by Django 5.0.6 on 2024-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_alter_coachingstaff_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstaff',
            name='club',
            field=models.CharField(default='Default Club', max_length=50),
        ),
    ]
