# Generated by Django 5.0.6 on 2024-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0021_alter_coachingstaff_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.CharField(default='Default Coach', max_length=100),
        ),
    ]
