# Generated by Django 5.0.6 on 2024-06-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0022_club_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='coach',
            new_name='coach_name',
        ),
    ]
