# Generated by Django 5.0.6 on 2024-06-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0024_alter_club_coach_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach_name',
            field=models.CharField(max_length=100),
        ),
    ]
