# Generated by Django 5.0.6 on 2024-06-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_alter_club_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturematch',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='football.team'),
        ),
        migrations.AddField(
            model_name='fixturematch',
            name='team_away',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='football.club'),
        ),
        migrations.AddField(
            model_name='fixturematch',
            name='team_home',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='football.club'),
        ),
        migrations.AddField(
            model_name='resultmatch',
            name='goal_details_away',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultmatch',
            name='goal_details_home',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='home_ground',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='coach_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coachingstaff',
            name='experience',
            field=models.CharField(default='1 year', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
