# Generated by Django 5.0.6 on 2024-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_fixturematch_team_fixturematch_team_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='coach_photo',
            field=models.ImageField(default='coach_photos/default.jpg', upload_to='coach_photos/'),
        ),
    ]
