# Generated by Django 5.0.6 on 2024-06-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0027_club_coach_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('cm', models.FloatField(default=0.0)),
                ('kg', models.FloatField(default=0.0)),
                ('apps', models.IntegerField(default=0)),
                ('mins', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='Yellow Cards')),
                ('red_cards', models.IntegerField(default=0, verbose_name='Red Cards')),
                ('motm', models.IntegerField(default=0, verbose_name='Man of the Match')),
                ('rating', models.FloatField(default=0.0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.team')),
            ],
            options={
                'verbose_name_plural': 'Player Stats',
            },
        ),
    ]
