# Generated by Django 5.0.6 on 2024-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_playerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='apps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='motm',
            field=models.IntegerField(default=0, verbose_name='Man of the Match'),
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Red Cards'),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Yellow Cards'),
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
