# Generated by Django 5.0.6 on 2024-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_player_apps_player_assists_player_goals_player_mins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
