# Generated by Django 5.0.6 on 2024-07-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0030_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstaff',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_staff', to='football.club'),
        ),
        migrations.AlterField(
            model_name='coachingstaff',
            name='role',
            field=models.CharField(default='Trainer', max_length=100),
        ),
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Coach', max_length=100)),
                ('nationality', models.CharField(default='Unknown', max_length=100)),
                ('experience', models.CharField(default='1 year', max_length=50)),
                ('photo', models.ImageField(default='photos/staff/default.jpg', upload_to='photos/staff/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_staff', to='football.club')),
            ],
        ),
    ]
