# Generated by Django 5.0.6 on 2024-07-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_alter_coachingstaff_club_alter_coachingstaff_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstaff',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_staff', to='football.club'),
        ),
        migrations.AlterField(
            model_name='coachingstaff',
            name='role',
            field=models.CharField(default='Coach', max_length=100),
        ),
        migrations.AlterField(
            model_name='otherstaff',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_staff', to='football.club'),
        ),
    ]
