# Generated by Django 5.0.6 on 2024-07-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_alter_coachingstaff_club_alter_coachingstaff_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='team_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='fixturematch',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='fixturematch',
            name='team',
        ),
        migrations.RemoveField(
            model_name='resultmatch',
            name='goal_details_away',
        ),
        migrations.RemoveField(
            model_name='resultmatch',
            name='goal_details_home',
        ),
        migrations.RemoveField(
            model_name='resultmatch',
            name='team_a_score',
        ),
        migrations.RemoveField(
            model_name='resultmatch',
            name='team_b_score',
        ),
        migrations.AddField(
            model_name='resultmatch',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultmatch',
            name='score_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultmatch',
            name='score_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixturematch',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fixturematch',
            name='team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='football.team'),
        ),
        migrations.AlterField(
            model_name='fixturematch',
            name='team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='football.team'),
        ),
        migrations.AlterField(
            model_name='resultmatch',
            name='fixture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.fixture'),
        ),
        migrations.AlterField(
            model_name='fixturematch',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.competition'),
        ),
    ]
