# Generated by Django 5.0.6 on 2024-07-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0034_alter_fixturematch_competition_delete_teammatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixturematch',
            name='opponent',
        ),
    ]
