# Generated by Django 5.0.6 on 2024-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0039_stadium_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
