# Generated by Django 5.0.6 on 2024-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0040_match_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='logo',
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='match_logos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='match_logos/'),
        ),
    ]
