# Generated by Django 5.0.4 on 2024-07-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0042_blog_highlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='title',
            new_name='headline',
        ),
    ]
