# Generated by Django 5.0.4 on 2024-07-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0046_delete_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(help_text='URL of the blog image', max_length=1000),
        ),
    ]
