# Generated by Django 5.0.4 on 2024-07-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0047_remove_blog_url_alter_blog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique value for blog page URL', max_length=200, unique=True),
        ),
    ]
