# Generated by Django 5.0.4 on 2024-07-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0048_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
