# Generated by Django 5.0.4 on 2024-07-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0050_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image.jpg', help_text='URL of the blog image', max_length=1000),
        ),
    ]
