# Generated by Django 5.0.4 on 2024-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0051_blogpost_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(default='', help_text='URL of the blog image', max_length=1000),
        ),
    ]
