# Generated by Django 5.0.4 on 2024-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0052_alter_blogpost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_image_url',
            field=models.URLField(default='', help_text="URL of the author's image", max_length=1000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='day',
            field=models.CharField(default='', max_length=20),
        ),
    ]
