# Generated by Django 5.0.4 on 2024-07-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0053_blogpost_author_image_url_blogpost_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_image_url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_image',
            field=models.ImageField(blank=True, help_text="Upload the author's image", null=True, upload_to='author_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload the blog image', null=True, upload_to='blog_images/'),
        ),
    ]
