# Generated by Django 5.0.4 on 2024-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0054_remove_blogpost_author_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='day',
            field=models.CharField(blank=True, max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
