# Generated by Django 5.0.4 on 2024-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0058_remove_blogpost_photo_blogpost_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='highlights_images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
