# Generated by Django 5.0.4 on 2024-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0060_remove_blog_image_url_remove_blogpost_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
