# Generated by Django 5.0.4 on 2024-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0061_alter_highlight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team_a_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='team_b_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.TimeField(),
        ),
    ]
