# Generated by Django 5.0.4 on 2024-07-31 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0062_alter_fixture_team_a_name_alter_fixture_team_b_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='football.club'),
        ),
    ]
