# Generated by Django 5.0.1 on 2024-08-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0066_match_author_name_match_first_half_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('staff_type', models.CharField(choices=[('Coaching Staff', 'Coaching Staff'), ('Other Staff', 'Other Staff'), ('Club Match Staff', 'Club Match Staff')], max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/staff/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='football.club')),
            ],
        ),
        migrations.RemoveField(
            model_name='coachingstaff',
            name='club',
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='CoachingStaff',
        ),
    ]
