# Generated by Django 5.0.1 on 2024-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0067_staff_remove_coachingstaff_club_delete_highlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Head Coach', 'Head Coach'), ('Assistant Coach', 'Assistant Coach'), ('Physiotherapist', 'Physiotherapist'), ('Team Manager', 'Team Manager'), ('Scout', 'Scout')], max_length=100),
        ),
    ]
