# Generated by Django 5.0.1 on 2024-08-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0068_alter_staff_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherStaff',
        ),
    ]
