# Generated by Django 5.0.1 on 2024-08-20 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0069_delete_otherstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='apps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='mins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='motm',
            field=models.IntegerField(verbose_name='Man of the Match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.CharField(default='⭐', help_text='Emoji rating (e.g., ⭐, 🌟, etc.)', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(verbose_name='Red Cards'),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(verbose_name='Yellow Cards'),
        ),
    ]
