# Generated by Django 5.0.1 on 2024-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0070_alter_player_apps_alter_player_assists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.CharField(blank=True, help_text='Emoji rating (e.g., ⭐, 🌟, etc.)', max_length=2, null=True),
        ),
    ]
