# Generated by Django 5.0.1 on 2024-08-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0071_alter_player_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.CharField(blank=True, choices=[('⭐', '1 Star'), ('⭐⭐', '2 Stars'), ('⭐⭐⭐', '3 Stars'), ('⭐⭐⭐⭐', '4 Stars'), ('⭐⭐⭐⭐⭐', '5 Stars')], help_text='Emoji rating (e.g., ⭐⭐⭐⭐, ⭐⭐⭐⭐⭐)', max_length=6, null=True),
        ),
    ]
