# Generated by Django 5.0.1 on 2024-08-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0073_alter_blog_image_alter_blogpost_author_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='apps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='mins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='motm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(),
        ),
    ]
