# Generated by Django 5.0.1 on 2024-08-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0075_remove_result_fixture_fixtureresult_delete_fixture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('competition', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('team_a_name', models.CharField(max_length=255)),
                ('team_a_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('team_b_name', models.CharField(max_length=255)),
                ('team_b_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='club',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='is_home_team',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='team_a_logo',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='team_a_name',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='team_b_logo',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='team_b_name',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='time',
        ),
        migrations.RemoveField(
            model_name='fixtureresult',
            name='venue',
        ),
        migrations.AlterField(
            model_name='fixtureresult',
            name='minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixtureresult',
            name='result_photo',
            field=models.ImageField(blank=True, null=True, upload_to='result_photos/'),
        ),
        migrations.AddField(
            model_name='fixtureresult',
            name='fixture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='football.fixture'),
        ),
    ]
