# Generated by Django 5.0.1 on 2024-09-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0077_alter_fixtureresult_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
