# Generated by Django 5.0.1 on 2024-09-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0078_delete_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('Coaching Staff', 'Coaching Staff'), ('Other Staff', 'Other Staff'), ('Club Match Staff', 'Club Match Staff'), ('Software Developer', 'Software Developer'), ('Director', 'Director'), ('Project Manager', 'Project Manager'), ('Community Engager', 'Community Engager'), ('Contributors', 'Contributors')], max_length=100),
        ),
    ]
