# Generated by Django 5.0.1 on 2024-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0080_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to='staff_images/'),
        ),
    ]
