# Generated by Django 5.0.1 on 2024-09-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0081_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Head Coach', 'Head Coach'), ('Assistant Coach', 'Assistant Coach'), ('Director', 'Diretor'), ('Team Manager', 'Team Manager'), ('Community Engager', 'Community Engager'), ('Backend Developer', 'Frontend Developer')], max_length=100),
        ),
    ]
