# Generated by Django 5.0.1 on 2024-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0082_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Head Coach', 'Head Coach'), ('Assistant Coach', 'Assistant Coach'), ('Director', 'Diretor'), ('Project Manager', 'Project Manager'), ('Community Engager', 'Community Engager'), ('Backend Developer', 'Backend Developer'), ('Frontend developer', 'Frontend Developer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('Coaching Staff', 'Coaching Staff'), ('Other Staff', 'Other Staff'), ('Club Match Staff', 'Club Match Staff'), ('ligiopen staff', 'ligiopen staff')], max_length=100),
        ),
    ]
