# Generated by Django 5.0.1 on 2024-09-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0084_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='photo',
        ),
    ]
