# Generated by Django 5.0.1 on 2024-09-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0086_remove_player_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
    ]
