# Generated by Django 5.0.1 on 2024-09-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0087_remove_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
