# Generated by Django 5.0.1 on 2024-09-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0089_player_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
    ]
