# Generated by Django 5.0.1 on 2024-10-23 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "football",
            "0091_remove_player_red_cards_remove_player_yellow_cards_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Match",
            new_name="Matchday",
        ),
    ]
