# Generated by Django 5.0.1 on 2024-09-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0092_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
