# Generated by Django 5.0.1 on 2024-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0094_rename_match_matchday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtureresult',
            name='minute',
        ),
        migrations.AddField(
            model_name='fixtureresult',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
