# Generated by Django 5.0.1 on 2024-10-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0095_remove_fixtureresult_minute_fixtureresult_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixtureresult',
            old_name='time',
            new_name='time_taken',
        ),
    ]
