# Generated by Django 5.0.1 on 2024-10-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0097_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
