# Generated by Django 5.0.1 on 2024-10-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0098_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5),
        ),
    ]
