# Generated by Django 5.0.1 on 2024-10-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0099_alter_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='red_card_image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_card_image',
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
    ]
