# Generated by Django 5.0.1 on 2024-10-22 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0100_teamindividual_fixtureteam_resultteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.teamindividual'),
        ),
    ]
