# Generated by Django 5.0.1 on 2024-10-25 11:32

import football.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0102_merge_20241025_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='red_card_image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_card_image',
        ),
        migrations.AddField(
            model_name='player',
            name='red_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='coach_photo',
            field=models.ImageField(blank=True, default='defaults/coach_placeholder.png', null=True, upload_to=football.models.upload_to),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/club_placeholder.png', null=True, upload_to=football.models.upload_to),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/player_placeholder.png', null=True, upload_to=football.models.upload_to),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='defaults/staff_placeholder.png', upload_to='staff_images/'),
        ),
    ]
