# Generated by Django 5.0.1 on 2024-10-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0103_remove_player_red_card_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='red_card',
            new_name='red_cards',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='yellow_card',
            new_name='yellow_cards',
        ),
    ]
