# Generated by Django 5.0.1 on 2024-10-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0100_remove_player_red_card_image_and_more'),
        ('football', '0104_rename_red_card_player_red_cards_and_more'),
    ]

    operations = [
    ]
