name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install MySQL
    - name: Install MySQL
      run: sudo apt-get install -y mysql-server

    # Start MySQL service
    - name: Start MySQL service
      run: sudo service mysql start

    # Set up MySQL database and user
    - name: Setup MySQL database
      run: |
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS ligiopen;"
        sudo mysql -e "CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY '';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON ligiopen.* TO 'root'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Verify qrcode module installation
      run: |
        python -m pip show qrcode

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test
