name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ligiopen
          MYSQL_USER: user
          MYSQL_PASSWORD: ""
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify qrcode module installation
      run: |
        python -m pip show qrcode

    - name: Run migrations
      env:
        DATABASE_NAME: ligiopen
        DATABASE_USER: user
        DATABASE_PASSWORD: ""
        DATABASE_HOST: localhost
        DATABASE_PORT: 3306
      run: python manage.py migrate

    - name: Run tests
      env:
        DATABASE_NAME: ligiopen
        DATABASE_USER: user
        DATABASE_PASSWORD: ""
        DATABASE_HOST: localhost
        DATABASE_PORT: 3306
      run: python manage.py test
