name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Remove or update this section if not using email
    # - name: Set environment variables
    #   run: echo "EMAIL_HOST_USER=<your_email_user>" >> $GITHUB_ENV

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test
