name: Django CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]


    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}  # Ensure this secret is set
          MYSQL_DATABASE: ligiopen
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Wait for MySQL to be ready
      run: |
        set -x
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for MySQL..."
          sleep 10
        done
        echo "MySQL is up and running"


    - name: Run migrations
      run: python manage.py migrate


    - name: Run tests
      run: python manage.py test


