name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7  # You can specify a MySQL version here
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=10s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: ligiopen
        ports:
          - 3306:3306
        # Wait for the MySQL service to start

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Verify qrcode module installation
      run: |
        python -m pip show qrcode

    - name: Run migrations
      run: python manage.py migrate
      env:
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 3306
        DATABASE_NAME: ligiopen
        DATABASE_USER: root
        DATABASE_PASSWORD: ""

    - name: Run tests
      run: python manage.py test
      env:
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 3306
        DATABASE_NAME: ligiopen
        DATABASE_USER: root
        DATABASE_PASSWORD: ""
