name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: [3.11 , 3.12]

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run application
      run: |
        python my_app.py
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
